# Generated by Django 2.0.7 on 2018-09-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picking_date',
            field=models.CharField(max_length=160, null=True, verbose_name='Date et Heure de Retrait'),
        ),
    ]
