# Generated by Django 2.0.7 on 2018-09-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_order_picking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='picking_date',
            field=models.DateTimeField(null=True, verbose_name='Date et Heure de Retrait'),
        ),
    ]
