# Generated by Django 2.0.7 on 2018-09-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_auto_20180827_2210'),
        ('commandes', '0003_auto_20180902_1934'),
    ]

    operations = [
    ]
