# Generated by Django 2.0.7 on 2018-09-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_merge_20180902_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='picking_date',
        ),
    ]
