# Generated by Django 2.0 on 2018-09-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0010_auto_20180908_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.Sous_Categories_Article', verbose_name='Catégorie Article'),
        ),
    ]
