# Generated by Django 2.1.2 on 2019-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0014_auto_20180909_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
