# Generated by Django 2.1.2 on 2019-04-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0015_orderitem_taux_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='taux_tva',
            field=models.CharField(max_length=100),
        ),
    ]
