# Generated by Django 2.1.2 on 2019-04-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0016_auto_20190411_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
