# Generated by Django 2.1.2 on 2019-04-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0017_auto_20190411_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='taux_tva',
        ),
    ]
