# Generated by Django 2.0.7 on 2018-07-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=160, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=160, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('code_postal', models.CharField(max_length=5, verbose_name='Code Postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commandes.Order')),
                ('product', models.ManyToManyField(max_length=1000, to='catalogue.Variations_Articles', verbose_name='Article')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Sous_Categories_Article', verbose_name='Catégorie Article')),
            ],
        ),
    ]
