# Generated by Django 2.0.7 on 2018-07-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, verbose_name='Code Postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='nom',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prenom',
            field=models.CharField(blank=True, max_length=160, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ville',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
    ]
