# Generated by Django 2.0.7 on 2018-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_order_picking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_order',
            field=models.BooleanField(default=False),
        ),
    ]
