# Generated by Django 2.0 on 2018-09-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_order_closed_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-picking_date', '-closed_order')},
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_order',
            field=models.BooleanField(default=False, verbose_name='Commande cloturée (cocher si terminée)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.Sous_Categories_Article', verbose_name='Catégorie Article'),
        ),
    ]
