# Generated by Django 2.1.2 on 2019-04-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20190101_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='taux_TVA',
        ),
        migrations.AddField(
            model_name='variations_articles',
            name='taux_TVA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogue.Taux_TVA'),
            preserve_default=False,
        ),
    ]
