# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:02
from __future__ import unicode_literals

import catalogue.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name="Nom de l'article")),
                ('slug', models.CharField(max_length=160)),
                ('image', models.ImageField(upload_to=catalogue.models.upload_location_articles)),
                ('disponible', models.BooleanField(verbose_name='Disponible / Non disponible')),
                ('allergenes', models.TextField()),
                ('gluten_info', models.BooleanField(verbose_name='Contient du Gluten: Oui / Non')),
                ('vegeterien_info', models.BooleanField(verbose_name='Végéterien friendly: Oui / Non')),
                ('ingredients', models.TextField()),
                ('producteurs', models.TextField()),
                ('unite_produit', models.CharField(max_length=160)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('taux_TVA', models.CharField(max_length=160)),
                ('description_produit', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('sous_categories_articles', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Categories_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name='Nom de la catégorie')),
                ('slug', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Categories_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name='Nom de la sous-catégorie')),
                ('slug', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=catalogue.models.upload_location_sous_categorie)),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix de l'article le plus bas de la catégorie")),
                ('publier', models.BooleanField(verbose_name='Activer / Désactiver la catégorie')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('categorie', models.ManyToManyField(to='catalogue.Categories_article')),
            ],
            options={
                'verbose_name': 'Catégorie des articles',
                'verbose_name_plural': 'Catégories des articles',
                'ordering': ['nom', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Sous_Categories_article'),
        ),
    ]
