# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories_article',
            name='presentation_categorie',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
