# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:01
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variations_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article_variation', models.CharField(max_length=160, verbose_name="Nom de la variation de l'article")),
                ('type_article', models.CharField(max_length=160)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('variation_disponible', models.BooleanField(verbose_name='Variation Disponible / Non disponible')),
                ('unite_oeuvre', models.CharField(max_length=160, verbose_name="Unité d'oeuvre")),
                ('quantite_mise_en_oeuvre', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_revient', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_disponible', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('producteurs', models.ManyToManyField(blank=True, to='producteurs.Producteurs')),
            ],
            options={
                'ordering': ['nom_article_variation'],
                'verbose_name_plural': 'Variations_Articles Articles',
                'verbose_name': 'Variation Article',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='unite_produit',
        ),
    ]
