# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20180626_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations_articles',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Article'),
            preserve_default=False,
        ),
    ]
