# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_taux_tva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taux_tva',
            options={'verbose_name': 'Taux TVA applicables', 'verbose_name_plural': 'Taux TVA applicables'},
        ),
        migrations.AlterField(
            model_name='article',
            name='taux_TVA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Taux_TVA'),
        ),
    ]
