# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_categories_article_presentation_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Sous_Categories_Article'),
            preserve_default=False,
        ),
    ]
