# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20180116_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_article',
            field=models.BooleanField(default=0, verbose_name="Article servant de base (cocher si oui) / Article servant d'ingrédients(laisser vide)"),
            preserve_default=False,
        ),
    ]
