# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20171105_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='producteurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producteurs.Producteurs'),
        ),
    ]
