# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20180626_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations_articles',
            name='categories',
        ),
        migrations.AddField(
            model_name='variations_articles',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Sous_Categories_Article'),
            preserve_default=False,
        ),
    ]
