# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20171029_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_article',
            options={'ordering': ['nom', 'timestamp'], 'verbose_name': 'Catégorie générale', 'verbose_name_plural': 'Catégories générale'},
        ),
        migrations.AlterModelOptions(
            name='sous_categories_article',
            options={'ordering': ['nom', 'timestamp'], 'verbose_name': 'Sous-Catégorie des articles', 'verbose_name_plural': 'Sous-Catégories des articles'},
        ),
        migrations.AddField(
            model_name='categories_article',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories_article',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Sous_Categories_Article'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='categorie',
            field=models.ManyToManyField(to='catalogue.Categories_Article'),
        ),
    ]
