# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20180626_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Variations_Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_variation_article', models.CharField(max_length=160, verbose_name='Type de Variations (Bases / Ingrédients / Plats Prêts')),
                ('slug', models.CharField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name_plural': 'Type de Variations Articles',
                'verbose_name': 'Type de Variations Articles',
            },
        ),
        migrations.AlterField(
            model_name='taux_tva',
            name='nom_taux_applicable',
            field=models.CharField(max_length=160, verbose_name='Taux TVA applicable'),
        ),
    ]
