# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20171113_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='producteurs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='producteurs.Producteurs'),
        ),
    ]
