# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20180628_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations_articles',
            name='type_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Type_Variations_Articles'),
        ),
    ]
