# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20171029_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_article',
            options={'ordering': ['nom', 'timestamp'], 'verbose_name': 'Catégorie générale', 'verbose_name_plural': 'Catégories générales'},
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Sous_Categories_Article'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='categorie',
            field=models.ManyToManyField(to='catalogue.Categories_Article'),
        ),
    ]
