# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0007_categories_categorie_principale'),
        ('catalogue', '0006_auto_20171113_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='producteurs',
        ),
        migrations.AddField(
            model_name='article',
            name='producteurs',
            field=models.ManyToManyField(blank=True, to='producteurs.Producteurs'),
        ),
    ]
