# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0007_categories_categorie_principale'),
        ('catalogue', '0007_auto_20171113_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='producteurs',
        ),
        migrations.AddField(
            model_name='article',
            name='producteurs',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='producteurs.Producteurs'),
            preserve_default=False,
        ),
    ]
