# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20171029_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_article',
            options={'ordering': ['nom', 'timestamp'], 'verbose_name': 'Catégorie Générale', 'verbose_name_plural': 'Catégories Générales'},
        ),
        migrations.AddField(
            model_name='categories_article',
            name='ordre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Sous_Categories_Article'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='categorie',
            field=models.ManyToManyField(to='catalogue.Categories_Article'),
        ),
    ]
