# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20180628_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unite_Produit',
            new_name='Unite_Oeuvre',
        ),
    ]
