# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-28 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20180628_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations_articles',
            name='unite_oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Oeuvre', verbose_name="Unité d'oeuvre"),
        ),
    ]
