# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20180628_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories_article',
            name='rubrique_principale',
            field=models.BooleanField(default=0, verbose_name='Catégorie Principale'),
            preserve_default=False,
        ),
    ]
