# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20171114_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_plat_info',
            field=models.BooleanField(default=0, verbose_name='Se consomme chaud (cocher) / froid (ne pas cocher)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='gluten_info',
            field=models.BooleanField(verbose_name='Contient du Gluten: Oui (cocher) / Non (ne pas cocher)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='vegeterien_info',
            field=models.BooleanField(verbose_name='Végéterien friendly: Oui (cocher) / Non (ne pas cocher)'),
        ),
    ]
