# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20171101_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories_article',
            options={'verbose_name': 'Catégorie Générale', 'verbose_name_plural': 'Catégories Générales'},
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Sous_Categories_Article'),
        ),
        migrations.AlterField(
            model_name='categories_article',
            name='actif',
            field=models.BooleanField(verbose_name='Actif / Inactif'),
        ),
        migrations.AlterField(
            model_name='categories_article',
            name='ordre',
            field=models.IntegerField(unique=True, verbose_name='Ordre des rubriques dans le menu'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='categorie',
            field=models.ManyToManyField(to='catalogue.Categories_Article'),
        ),
    ]
