# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_categories_article_rubrique_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations_articles',
            name='article_une',
            field=models.BooleanField(default=0, verbose_name='Article en une? / Cocher si oui.'),
            preserve_default=False,
        ),
    ]
