# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20171118_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allergenes',
            field=models.TextField(blank=True),
        ),
    ]
