# Generated by Django 2.0.7 on 2018-07-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_variations_articles_article_une'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sous_categories_articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Type_Produit', verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='taux_TVA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Taux_TVA'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Categories_Article'),
        ),
        migrations.AlterField(
            model_name='variations_articles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Article'),
        ),
        migrations.AlterField(
            model_name='variations_articles',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Sous_Categories_Article'),
        ),
        migrations.AlterField(
            model_name='variations_articles',
            name='type_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Type_Variations_Articles'),
        ),
        migrations.AlterField(
            model_name='variations_articles',
            name='unite_oeuvre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Unite_Oeuvre', verbose_name="Unité d'oeuvre"),
        ),
    ]
