# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20171118_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name="Nom de l'allergie")),
                ('active', models.BooleanField(verbose_name='Actif / Inactif')),
            ],
        ),
    ]
