# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_allergie'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergie',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergie',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
