# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20171104_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='catalogue.Sous_Categories_Article'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='categorie',
            field=models.ManyToManyField(to='catalogue.Categories_Article'),
        ),
        migrations.AlterField(
            model_name='sous_categories_article',
            name='plats',
            field=models.BooleanField(verbose_name='Fait partie de la rubrique "Plats"'),
        ),
    ]
