# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20171118_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergie',
            name='slug',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
