# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20171118_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergie',
            options={'ordering': ['nom', 'timestamp'], 'verbose_name': 'Allergie', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='allergenes',
        ),
        migrations.AddField(
            model_name='article',
            name='allergenes',
            field=models.ManyToManyField(blank=True, to='catalogue.Allergie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
