# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_unite_produit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unite_produit',
            options={'ordering': ['nom', 'timestamp'], 'verbose_name': 'Unité du produit', 'verbose_name_plural': 'Unité du produit'},
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
    ]
