# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20171123_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='nom',
            field=models.CharField(max_length=160, verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
        migrations.AlterField(
            model_name='type_produit',
            name='nom',
            field=models.CharField(max_length=160, verbose_name='Catégorie du produi'),
        ),
    ]
