# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20171123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sous_categories_articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Type_Produit', verbose_name="Type d'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
    ]
