# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20171123_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sous_categories_article',
            name='composer',
            field=models.BooleanField(default=0, verbose_name='Possibilité de composer (cocher) / impossible de composer (vide)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
    ]
