# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20171126_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
        migrations.AlterField(
            model_name='type_produit',
            name='nom',
            field=models.CharField(max_length=160, verbose_name='Catégorie du produit'),
        ),
    ]
