# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20171203_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='nom',
            field=models.CharField(max_length=160, verbose_name="Nom de l'allergie"),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
        migrations.AlterField(
            model_name='unite_produit',
            name='nom',
            field=models.CharField(max_length=160, verbose_name='Unité du produit'),
        ),
    ]
