# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_auto_20171203_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_composer',
            field=models.BooleanField(default=1, verbose_name='Article servant à composer / ajout complémentaire recette'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
    ]
