# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_auto_20171203_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_composer',
            field=models.BooleanField(verbose_name='Article servant à composer un plat (cocher si oui)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Unite_Produit'),
        ),
    ]
