# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import producteurs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_personnes', models.CharField(max_length=160, verbose_name='Catégorie de producteurs / Equipier')),
                ('slug', models.CharField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('actif', models.BooleanField()),
                ('ordre', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Catégorie personnel / producteur',
                'verbose_name_plural': 'Catégories personnel / producteur',
                'ordering': ['categorie_personnes', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Equipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name="Nom de l'équipier")),
                ('prenom', models.CharField(max_length=160, verbose_name="Prénom de l'équipier")),
                ('photo_equipier', models.ImageField(upload_to=producteurs.models.upload_location_equipe, verbose_name="Photo de l'équipier")),
                ('description', models.TextField(verbose_name="Description de l'équipier")),
                ('poste', models.CharField(max_length=160, verbose_name="Poste occupé par l'équipier")),
                ('actif', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipe',
            },
        ),
        migrations.CreateModel(
            name='Producteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=160, verbose_name='Nom du producteur')),
                ('prenom', models.CharField(max_length=160, verbose_name='Prénom du producteur')),
                ('photo_producteur', models.ImageField(upload_to=producteurs.models.upload_location_producteurs)),
                ('description', models.TextField(verbose_name='Description du producteur')),
                ('actif', models.BooleanField()),
                ('rue', models.CharField(max_length=160, verbose_name='Rue du producteur')),
                ('code_postal', models.CharField(max_length=160, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=160, verbose_name='Ville / Localité')),
                ('pays', models.CharField(max_length=160, verbose_name='Pays')),
                ('numero_telephone', models.CharField(max_length=160, verbose_name='N° de Téléphone / de Contact')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
            },
        ),
        migrations.CreateModel(
            name='Sous_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_categorie_personnes', models.CharField(max_length=160, verbose_name='Catégorie de producteurs / Equipier')),
                ('slug', models.CharField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('actif', models.BooleanField()),
                ('categorie_producteurs', models.ManyToManyField(to='producteurs.Categories')),
            ],
            options={
                'verbose_name': 'Sous-Catégorie',
                'verbose_name_plural': 'Sous-Catégories',
                'ordering': ['sous_categorie_personnes', 'timestamp'],
            },
        ),
        migrations.AddField(
            model_name='producteurs',
            name='categorie_producteurs',
            field=models.ManyToManyField(to='producteurs.Sous_Categories'),
        ),
        migrations.AddField(
            model_name='equipes',
            name='categorie_personnel',
            field=models.ManyToManyField(to='producteurs.Sous_Categories'),
        ),
    ]
