# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipes',
            old_name='photo_equipier',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='producteurs',
            old_name='photo_producteur',
            new_name='photo',
        ),
    ]
