# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0004_auto_20171111_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.CharField(default=1, max_length=160, verbose_name='Présentation de la catégorie de personnes'),
            preserve_default=False,
        ),
    ]
