# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0005_categories_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sous_categories',
            name='categorie_producteurs',
        ),
        migrations.AlterField(
            model_name='equipes',
            name='categorie_personnel',
            field=models.ManyToManyField(to='producteurs.Categories'),
        ),
        migrations.AlterField(
            model_name='producteurs',
            name='categorie_producteurs',
            field=models.ManyToManyField(to='producteurs.Categories'),
        ),
        migrations.DeleteModel(
            name='Sous_Categories',
        ),
    ]
