# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0006_auto_20171112_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categorie_principale',
            field=models.BooleanField(default=1, verbose_name="S'agit-il d'une catégaorie principale?"),
            preserve_default=False,
        ),
    ]
